plugins {
	id 'java'
	id 'org.springframework.boot' version '2.7.6'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id "org.sonarqube" version "5.1.0.4882"
}

group = 'com.k-paas'

java {
	sourceCompatibility = '1.8'
}

ext {
	set('springCloudVersion', "2021.0.8")
}

repositories {
	mavenCentral()
}

jar {
	enabled = true
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	implementation "org.springframework.cloud:spring-cloud-starter-openfeign"
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	compileOnly("org.springframework.boot:spring-boot-devtools")
	implementation 'org.projectlombok:lombok'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

task checkFilesExist {
    doLast {
        def directory = file('build/classes/java/main')
        if (directory.exists() && directory.isDirectory()) {
            def files = directory.listFiles()
            if (files && files.length > 0) {
                println "Files in ${directory} directory:"
                files.each { file -> println file.name }
            } else {
                println "No files found in ${directory} directory."
            }
        } else {
            println "${directory} does not exist or is not a directory."
        }
    }
}

build.dependsOn checkFilesExist

sonarqube {
    properties {
        property "sonar.projectKey", "task_msa_ui"
        property "sonar.projectName", "task_msa_ui"
        property "sonar.projectVersion", "1.0"
        property "sonar.java.binaries", "$buildDir/classes"
    }
}

